import { initHomePage } from "./pages/home";
import { initStartComponent } from "./components/start";
import { initPlayComponent } from "./components/play";
import { initButtonComponent } from "./components/button";
import { initDecisionComponent } from "./components/decision";
import { initScoreComponent } from "./components/score";
import { initRouter } from "./router";
import { state } from "./state";
const bakcgroundURL = new URL("./fondo.svg", import.meta.url);
(function () {
  state.initStorage();
  initStartComponent();
  initButtonComponent();
  initPlayComponent();
  initDecisionComponent();
  initScoreComponent();
  const rootEl: any = document.querySelector(".root");
  rootEl.style.background = ` url(${bakcgroundURL}) no-repeat`;
  rootEl.style.backgroundSize = `cover`;
  initRouter(rootEl);
})();
